const SOLD_OUT = "SOLD_OUT"
const TOO_MANY = "TOO_MANY"
const NOT_FOUND = "NOT_FOUND"
const SHIPPING_LABEL_ERROR = "SHIPPING_LABEL_ERROR"
const SHIPPING_RATE_ERROR = "SHIPPING_RATE_ERROR"
const SHIPENGINE_ERROR = "SHIPENGINE_ERROR"
const CUSTOMERS_API_ERROR = "CUSTOMERS_API_ERROR"
const ORDERS_API_ERROR = "ORDERS_API_ERROR"
const PAYMENTS_API_ERROR = "PAYMENTS_API_ERROR"
const EMAILJS_ERROR = "EMAILJS_ERROR"
const SERVER_ERROR = "SERVER_ERROR"
const CARDS_API_ERROR = "CARD_API_ERROR"
const BAD_REQUEST = "BAD_REQUEST"

module.exports = {
  SOLD_OUT,
  TOO_MANY,
  NOT_FOUND,
  SHIPPING_LABEL_ERROR,
  SHIPPING_RATE_ERROR,
  SHIPENGINE_ERROR,
  CUSTOMERS_API_ERROR,
  ORDERS_API_ERROR,
  PAYMENTS_API_ERROR,
  EMAILJS_ERROR,
  SERVER_ERROR,
  CARDS_API_ERROR,
  BAD_REQUEST
}